# Generated by Django 5.2.4 on 2025-10-09 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$', 'Formato RUT inválido (ej: 12.345.678-9).')]),
        ),
    ]
