# Generated by Django 5.2.7 on 2025-10-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_es_admin_alter_perfil_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos_carrusel', models.JSONField(blank=True, default=list, null=True)),
                ('numero_contacto', models.CharField(max_length=15)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
