# Generated by Django 5.2.7 on 2025-10-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionhomes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionHomes',
        ),
        migrations.AlterField(
            model_name='configuracionhome',
            name='fotos_carrusel',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
