# Generated by Django 5.2.7 on 2025-10-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_configuracionhomes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='orden',
            name='ccomprobante',
            field=models.TextField(blank=True, help_text='Nota o enlace a comprobante de transferencia (opcional).', null=True),
        ),
    ]
