# Generated by Django 5.2.4 on 2025-12-03 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_configuracionhome_options_alter_perfil_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Ingresa RUT sin puntos ni espacios (ej: 11527103-2 o 11527103-K)', regex='^\\d{7,8}-[\\dKk]$')]),
        ),
    ]
