# Generated by Django 5.2.4 on 2025-12-04 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_perfil_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='orden',
            name='mensaje_cliente',
            field=models.TextField(blank=True, help_text='Mensaje opcional del cliente'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(help_text='Ejemplo: 11527103-2', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato RUT inválido. Usa: 12345678-9 o 1234567-K (sin puntos)', regex='^\\d{7,8}-[\\dKk]$')]),
        ),
    ]
