# Generated by Django 5.2.7 on 2025-12-04 03:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orden_comprobante_orden_mensaje_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_por_unidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_hijo',
            field=models.ForeignKey(blank=True, help_text='Si este producto es una caja/paquete, aquí va el producto individual que contiene', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_padre', to='core.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamano_paquete',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Ej: 10 para caja de 10 bolsas, o 5.5 para caja de 5.5 kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('UN', 'Unidad / Bolsa'), ('CJ', 'Caja')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
    ]
