# Generated by Django 5.2.4 on 2025-12-04 19:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_producto_precio_producto_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionhome',
            options={},
        ),
        migrations.RemoveField(
            model_name='orden',
            name='ccomprobante',
        ),
        migrations.AddField(
            model_name='orden',
            name='nota_comprobante',
            field=models.TextField(blank=True, help_text='Link o nota del comprobante (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='comprobante',
            field=models.ImageField(blank=True, help_text='Foto del comprobante de pago', null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(help_text='Ejemplo: 11527103-2', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato RUT inválido', regex='^\\d{7,8}-[\\dKk]$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_hijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_padre', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano_paquete',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Ej: 10 para caja de 10 unidades', max_digits=10),
        ),
    ]
