# Generated by Django 5.2.4 on 2025-12-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_configuracionhome_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_por_unidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio'),
        ),
    ]
