# Generated by Django 5.2.7 on 2025-12-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_producto_precio_por_unidad_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Se genera automáticamente si lo dejas vacío', max_length=50, null=True, unique=True),
        ),
    ]
