# Generated by Django 5.2.4 on 2025-12-06 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_producto_codigo_barras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('retiro', 'Retiro en local'), ('domicilio', 'Envío a domicilio')], default='retiro', max_length=20)),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('comuna', models.CharField(blank=True, choices=[('Alhué', 'Alhué'), ('Buin', 'Buin'), ('Calera de Tango', 'Calera de Tango'), ('Cerrillos', 'Cerrillos'), ('Cerro Navia', 'Cerro Navia'), ('Colina', 'Colina'), ('Conchalí', 'Conchalí'), ('Curacaví', 'Curacaví'), ('El Bosque', 'El Bosque'), ('El Monte', 'El Monte'), ('Estación Central', 'Estación Central'), ('Huechuraba', 'Huechuraba'), ('Independencia', 'Independencia'), ('Isla de Maipo', 'Isla de Maipo'), ('La Cisterna', 'La Cisterna'), ('La Florida', 'La Florida'), ('La Granja', 'La Granja'), ('La Pintana', 'La Pintana'), ('La Reina', 'La Reina'), ('Las Condes', 'Las Condes'), ('Lo Barnechea', 'Lo Barnechea'), ('Lo Espejo', 'Lo Espejo'), ('Lo Prado', 'Lo Prado'), ('Macul', 'Macul'), ('Maipú', 'Maipú'), ('María Pinto', 'María Pinto'), ('Melipilla', 'Melipilla'), ('Ñuñoa', 'Ñuñoa'), ('Padre Hurtado', 'Padre Hurtado'), ('Paine', 'Paine'), ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'), ('Peñaflor', 'Peñaflor'), ('Peñalolén', 'Peñalolén'), ('Pirque', 'Pirque'), ('Providencia', 'Providencia'), ('Pudahuel', 'Pudahuel'), ('Puente Alto', 'Puente Alto'), ('Quilicura', 'Quilicura'), ('Quinta Normal', 'Quinta Normal'), ('Recoleta', 'Recoleta'), ('Renca', 'Renca'), ('San Bernardo', 'San Bernardo'), ('San Joaquín', 'San Joaquín'), ('San José de Maipo', 'San José de Maipo'), ('San Miguel', 'San Miguel'), ('San Pedro', 'San Pedro'), ('San Ramón', 'San Ramón'), ('Santiago', 'Santiago'), ('Talagante', 'Talagante'), ('Til Til', 'Til Til'), ('Vitacura', 'Vitacura')], max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='core.orden')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Ej: Casa, Trabajo, Mamá')),
                ('calle', models.CharField(max_length=200, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número / Depto')),
                ('comuna', models.CharField(choices=[('Alhué', 'Alhué'), ('Buin', 'Buin'), ('Calera de Tango', 'Calera de Tango'), ('Cerrillos', 'Cerrillos'), ('Cerro Navia', 'Cerro Navia'), ('Colina', 'Colina'), ('Conchalí', 'Conchalí'), ('Curacaví', 'Curacaví'), ('El Bosque', 'El Bosque'), ('El Monte', 'El Monte'), ('Estación Central', 'Estación Central'), ('Huechuraba', 'Huechuraba'), ('Independencia', 'Independencia'), ('Isla de Maipo', 'Isla de Maipo'), ('La Cisterna', 'La Cisterna'), ('La Florida', 'La Florida'), ('La Granja', 'La Granja'), ('La Pintana', 'La Pintana'), ('La Reina', 'La Reina'), ('Las Condes', 'Las Condes'), ('Lo Barnechea', 'Lo Barnechea'), ('Lo Espejo', 'Lo Espejo'), ('Lo Prado', 'Lo Prado'), ('Macul', 'Macul'), ('Maipú', 'Maipú'), ('María Pinto', 'María Pinto'), ('Melipilla', 'Melipilla'), ('Ñuñoa', 'Ñuñoa'), ('Padre Hurtado', 'Padre Hurtado'), ('Paine', 'Paine'), ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'), ('Peñaflor', 'Peñaflor'), ('Peñalolén', 'Peñalolén'), ('Pirque', 'Pirque'), ('Providencia', 'Providencia'), ('Pudahuel', 'Pudahuel'), ('Puente Alto', 'Puente Alto'), ('Quilicura', 'Quilicura'), ('Quinta Normal', 'Quinta Normal'), ('Recoleta', 'Recoleta'), ('Renca', 'Renca'), ('San Bernardo', 'San Bernardo'), ('San Joaquín', 'San Joaquín'), ('San José de Maipo', 'San José de Maipo'), ('San Miguel', 'San Miguel'), ('San Pedro', 'San Pedro'), ('San Ramón', 'San Ramón'), ('Santiago', 'Santiago'), ('Talagante', 'Talagante'), ('Til Til', 'Til Til'), ('Vitacura', 'Vitacura')], max_length=100)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Indicaciones')),
                ('predeterminada', models.BooleanField(default=False, verbose_name='Predeterminada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
