# Generated by Django 5.2.4 on 2025-12-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_direccionenvio_direccionguardada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionenvio',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_envio', to='core.orden'),
        ),
    ]
