# Generated by Django 5.2.4 on 2025-12-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_direccionenvio_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='temp_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
