# Generated by Django 6.0.3 on 2026-03-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_perfil_temp_token_perfil_token_expira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Texto alternativo para la imagen', max_length=100)),
                ('imagen', models.ImageField(upload_to='banners/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='0 aparece primero, 1 segundo, etc.')),
            ],
        ),
        migrations.RemoveField(
            model_name='orden',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='orden',
            name='comprobante_b64',
            field=models.TextField(blank=True, null=True, verbose_name='Comprobante (Base64)'),
        ),
    ]
