# Generated by Django 5.2.4 on 2026-04-07 19:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_banner_remove_orden_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_granel',
            field=models.BooleanField(default=False, verbose_name='¿Es producto a granel (se vende por kilogramos)?'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8),
        ),
    ]
