# Generated by Django 6.0.3 on 2026-04-13 02:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_producto_es_granel_alter_itemcarrito_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorden',
            options={'verbose_name': 'Ítem de Orden', 'verbose_name_plural': 'Ítems de Orden'},
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Cantidad en kg (3 decimales para gramos)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemorden_set', to='core.orden'),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nota_comprobante',
            field=models.TextField(blank=True, null=True),
        ),
    ]
