# Generated by Django 6.0.3 on 2026-04-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_itemorden_options_alter_itemorden_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='es_personalizado',
            field=models.BooleanField(default=False, help_text='True si el ítem fue agregado por monto (ej: $5.000 de queso)'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='monto_pesos',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Monto en pesos ingresado por el cliente (solo para productos granel)', max_digits=10, null=True),
        ),
    ]
