# Generated by Django 6.0.3 on 2026-04-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_itemcarrito_es_personalizado_itemcarrito_monto_pesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='cantidad_real_entregada',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cantidad real en kg (solo para pedidos personalizados)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='es_personalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='monto_pesos',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
