# Generated by Django 6.0.3 on 2026-04-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_itemorden_cantidad_real_entregada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='stock_descontado',
            field=models.BooleanField(default=False, help_text='Indica si ya se descontó stock de este ítem'),
        ),
    ]
