server {
    listen 80;

    # Servir archivos estáticos
    location /static/ {
        alias /static/;
        expires 30d;
        add_header Cache-Control "public";
    }

    # Servir archivos media (imágenes)
    location /media/ {
        alias /media/;
        expires 30d;
        add_header Cache-Control "public";
    }
}
